export default [
    {
        'name':'更新日志',
        'path':'/changelog'
    },
    {
        'name':'开发指南',
        'children':[
            {
                'title':'开始',
                'path':'/installation'
            },
            {
                'title':'Webpack 配置',
                'path':'/webpack'
            },
            {
                'title':'色彩',
                'path':'/color'
            }
        ]
    },
    {
        'name':'基础控件',
        'children':[
            {
                'title':'按钮',
                'path':'/button'
            },

            {
                'title':'输入框',
                'path':'/input'
            }
        ]
    },
    {
        'name':'容器',
        'children':[
            {
                'title':'主面板',
                'path':'/panel'
            },
            {
                'title':'折叠面板',
                'path':'/collapse'
            }
        ]
    },

]