export default {
    'zh-CN':[
        {
            'name':'更新日志',
            'path':'/changelog',
            'version':null,
            'content':[]
        },
        {
            'name':'开发指南',
            'version':null,
            'children':[
                {
                    'title':'开始',
                    'path':'/installation',
                    'content':[]
                },
                {
                    'title':'色彩',
                    'path':'/color',
                    'content':[]
                }
            ]
        },
        {
            'name':'基础控件',
            'version':null,
            'children':[
                {
                    'name':'按钮',
                    'path':'/button',
                    'content':[
                        'Button 按钮',
                        '基础用法',
                        '禁用状态',
                        '按钮组',
                        '加载中',
                        'Attributes',
                    ]
                },
                {
                    'name':'输入框',
                    'path':'/input',
                    'content':[]
                }
            ]
        }
    ],
    'zh_en_map':{
        '/button':{
            'Button 按钮':'button-an-niu',
            '基础用法':'ji-chu-yong-fa',
            '禁用状态':'jin-yong-zhuang-tai',
            '按钮组':'an-niu-zu',
            '加载中':'jia-zai-zhong',
            'Attributes':'attributes',
        }
    }
}