export default [
    {
        'name':'更新日志',
        'path':'/changelog'
    },
    {
        'name':'开发指南',
        'children':[
            {
                'title':'开始',
                'path':'/installation'
            },
            {
                'name':'色彩',
                'path':'/color'
            }
        ]
    },
    {
        'name':'基础控件',
        'children':[
            {
                'name':'按钮',
                'path':'/button'
            },
            {
                'name':'输入框',
                'path':'/input'
            }
        ]
    }

]